export const E2E_NAVIGATION_TIMEOUT_MS = 20_000
export const E2E_APP_VISIBLE_TIMEOUT_MS = 10_000
export const E2E_AUTH_SETUP_ATTEMPTS = 3
export const TIMELINE_OVERFLOW_COMMENT_COUNT = 12
export const TIMELINE_COMMENTS_SCROLL_OFFSET_PX = 600
export const TIMELINE_TOOLBAR_STICKY_TOLERANCE_PX = 1
