export const RELEASE_FEED_STARRED_REPOSITORY_PAGE_SIZE = 50
export const RELEASE_FEED_RELEASE_CANDIDATE_PAGE_SIZE = 5
export const RELEASE_FEED_BODY_PREVIEW_MAX_CHARACTERS = 220
export const RELEASE_FEED_MARKDOWN_COLLAPSED_MAX_HEIGHT = '4.1rem'
export const RELEASE_FEED_CARD_BORDER_RADIUS_PX = 8
export const RELEASE_FEED_AVATAR_SIZE_PX = 44
export const RELEASE_FEED_LOADING_SKELETON_COUNT = 3
export const RELEASE_FEED_LOADING_SKELETON_HEIGHT_PX = 132
